const BENCHMARK_FIGURES = [
  { chapter: '2d_Motion_From_3D', stem: 'basic_motion_point' },
  { chapter: '2d_Motion_From_3D', stem: 'flying_bird' },
  { chapter: '2d_Motion_From_3D', stem: 'yaw_pitch_roll' },
  { chapter: '3d_Learning', stem: 'geometry_reconstruction_12' },
  { chapter: '3d_Scene_Understanding_Stereo', stem: 'epipolar_geometry' },
  { chapter: 'Blurring_2', stem: 'bin2' },
  { chapter: 'Blurring_2', stem: 'box' },
  { chapter: 'Derivatives', stem: 'DFTderivativeoperators' },
  { chapter: 'Derivatives', stem: 'DFTlaplacians' },
  { chapter: 'Generative_Modeling_and_Rep_Learning', stem: 'rep_gen_schematic' },
  { chapter: 'Graphical_Models', stem: 'mrf' },
  { chapter: 'Homogeneous_Coordinates', stem: 'homogeneousAndHeteregeneous_VS3' },
  { chapter: 'Image_Processing_Fourier', stem: 'complexexponential' },
  { chapter: 'Imaging', stem: 'brdf' },
  { chapter: 'Imaging', stem: 'no_picture_on_a_wall_aina' },
  { chapter: 'Imaging', stem: 'orthogonal_projection' },
  { chapter: 'Imaging', stem: 'pinhole_geometry2' },
  { chapter: 'Imaging', stem: 'pinhole_names2' },
  { chapter: 'Imaging', stem: 'similar_triangles2' },
  { chapter: 'Neural_Nets_As_Distribution_Transformers', stem: '2D_mapping_diagrams' },
  { chapter: 'Neural_Nets_As_Distribution_Transformers', stem: 'nn_training_viz' },
  { chapter: 'Neural_Nets_As_Distribution_Transformers', stem: 'vit_mapping_plot' },
  { chapter: 'Homography', stem: 'homography_plane_geometry2' },
  { chapter: 'Imaging_Geometry', stem: 'pinhole_and_sensor' },
  { chapter: 'Imaging_Geometry', stem: 'reprojection_error' },
  { chapter: 'Optical_Flow', stem: 'barber_pole' },
  { chapter: 'VLMs', stem: 'clip_mapping_diagram_two_branch' },
  { chapter: 'Spatial_Filter_Sets', stem: 'gabor_spacetime_tiles' },
  { chapter: 'Spatial_Filter_Sets', stem: 'gabors' },
  { chapter: 'Upsamplig_downsampling_2', stem: 'bilinear_interp2' },
];

export default BENCHMARK_FIGURES;
